### ISSUE TITLE
Failed to activate the gitlab-manager package

### ISSUE THREAD

**Issue by himasindhu509** [T-Huelsken/gitlab-manager#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [gitlab-manager](https://github.com/T-Huelsken/gitlab-manager) package 0.2.1

### Stack Trace

Failed to activate the gitlab-manager package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'status-bar-gitlab'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'status-bar-gitlab'. A type with that name is already registered.
    at /packages/gitlab-manager/lib/status-bar-view.coffee:201:27)
    at /packages/gitlab-manager/lib/status-bar-view.coffee:1:1)
    at /packages/gitlab-manager/lib/status-bar-view.coffee:1:1)
    at Module.get_Module._compile (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/gitlab-manager/lib/gitlab-manager.coffee:4:17)
    at /packages/gitlab-manager/lib/gitlab-manager.coffee:1:1)
    at /packages/gitlab-manager/lib/gitlab-manager.coffee:1:1)
    at Module.get_Module._compile (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:1:714332)
    at Package.requireMainModule (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:3417381)
    at Package.activateNow (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:3405365)
    at measure (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:3405143)
    at Package.measure (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:3402753)
    at activationPromise.activationPromise.Promise (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:3405003)
    at /packages/git-plus/node_modules/core-js/modules/es6.promise.js:177:7)
    at Package.activate (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:3404946)
    at PackageManager.activatePackage (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:382285)
    at C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:937303
    at r (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:11:931909)
    at n (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:14:1128986)
    at t.bufferStream (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:14:1129140)
    at Socket.e.on (C:/ProgramData/Hima.n/atom/app-1.40.1/resources/app/static/<embedded>:14:1127742)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
 23x -0:53.2.0 core:move-down (div.panels-item)
```

### Non-Core Packages

```
atom-github-issues 0.4.3 
atom-review-vocab 0.1.1 
bitbucket-issues 0.1.1 
git-control 0.9.0 
git-control-fork 0.11.0 
git-menu 3.0.5 
git-plus 8.7.1 
git-plus-toolbar 1.0.1 
git-review-comments 0.2.0 
git-status 0.3.4 
git-tabs 0.4.1 
git-tools 0.5.0 
github-plus 1.0.0 
gitlab 0.1.3-7 
gitlab-integration 0.4.8 
gitlab-manager 0.2.1 
language-log 1.9.0 
minsky-link 0.0.16 
open-on-bitbucket 0.5.0 
pull-request 0.2.1 
show-repository-web 0.1.2 
teletype 0.13.4 
tool-bar 1.1.12 
```

**Comment by T-Huelsken** [comment]
Thanks for the issue. Like the readme already says it's kind of a fork of the gitlab-integration package. Therefore they are incompatible and can't be used at the same time. (e.g. both packages are using the class status-bar-gitlab which is causing your error). Try to remove gitlab-integration and restart atom again. It should be working fine again.
Will update the readme later.
